export const SUBMIT_USER_SUCCESS = 'SUBMIT_USER_SUCCESS';
export const SUBMIT_USER_FAILURE = 'SUBMIT_USER_FAILURE';
export const SUBMIT_SUCCESS_ASYNC = 'SUBMIT_SUCCESS_ASYNC';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_SUCCESS_ASYNC = 'FETCH_USER_ASYNC';